baseURL = "https://jphen.de"
languageCode = "en-us"
title = "JP's Home"
theme = "hugo-theme-shell"

[Params]

 #Additions start here
  [Params.Navbar]
  use = true
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
    # Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "JP's Portfolio"
  
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  # scheme = "shell-ubuntu"
  # schema = "monokai"
  schema = "ubuntu"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "jp"
  pcName = "home"
  workDir = ""
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  Hi I am Jp!
  
  This Is just a digital calling card
  to give a quick overview of my activities
  and a tiny glimpse into my personal history.

  Xoxo
  stay open minded

  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

    [Params.Tree]
    use = true
    folderName = "my_projects"
    # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
    files = [
        ["JPSec", "/works/jpsec.md"],
        ["JPSecure.IT", "/works/jpsecureit.md"],
        ["AllAroundNetwork", "/works/allaround.md"],
        ["DarkSite-Gaming", "/works/darksite-gaimg.md"],
        ["XING", "https://www.example.com/"],
        ["LinkedIN", "https://www.example.com/"]
    ]
	
[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
